name: Build and Upload Ladybird

on:
  workflow_dispatch:

jobs:
  build-macos:
    name: Build for macOS (Intel)
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Select available Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Install Homebrew dependencies
        run: brew install autoconf autoconf-archive automake bash ccache coreutils llvm@20 nasm ninja pkg-config qt unzip wabt

      - name: Set environment for Homebrew Clang
        run: |
          echo "CC=$(brew --prefix llvm@20)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm@20)/bin/clang++" >> $GITHUB_ENV

      - name: Build Ladybird
        run: ./Meta/ladybird.py build ladybird

      - name: Package artifacts
        run: |
          cd Build/release/bin
          zip -r ../../../ladybird-macos-intel.zip Ladybird.app
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ladybird-macos-intel
          path: ladybird-macos-intel.zip
